### PR TITLE
Train Panic Path Issue Fix

### PR DESCRIPTION
**Pull request by SlyWerewolfAJ**
## Pull request contents:
- [ ] Add map
    - [x] I am the author or I have obtained permission from the author
- [x] Remove or update existing map (give details as to what and why)

## Details:
-Removed Hiking Trail Path
-Changed Pre-Build Layout
-Changed Pre-Build Ride to Not Anger The Situation
-Starting Cash Changed From 100000 to 125000

### CODE REVIEW

**Comment by SlyWerewolfAJ** [comment]
. . . Check failed due to Time-out on a map that wasn't changed

**Comment by CorySanin** [comment]
It's failing on the very first one. So there's probably something wrong with the pipeline tools. I'll try re-running it, but it will probably fail again.

**Comment by SlyWerewolfAJ** [comment]
Wooooooooooo! It works now!

**Comment by CorySanin** [comment]
It's missing staff. Please check the [checklist](https://github.com/CorySanin/ffa-tycoon-parks#requirements)

**Comment by CorySanin** [comment]
Is the drop in starting funds from 175000 to 125000 intentional?

**Comment by SlyWerewolfAJ** [comment]
That means something was off when I loaded it up trying to calculate the cash amount. I will change it back.

**Review by CorySanin — APPROVED** [review]

**Pull request merged**
